### ISSUE TITLE
docker-compose not configuring

### ISSUE THREAD

**Issue by FlorianTolk** [gesellix/couchdb-cluster-config#2]
I have tried standing this repository up both on Ubuntu 16.04 and Ubuntu 18.04

After starting the docker swarm, the three couchdb instances start up in the network just fine. However, the cluster-setup service doesn't work and I need to configure it manually.

When looking at the console, it looks like docker-compose is trying to run the cluster setup before the actual couchDB containers are stood up.

**Comment by gesellix** [comment]
The tool should perform retries before actually trying to setup the cluster. See https://github.com/gesellix/couchdb-cluster-config/blob/55b53b83dcee4ca4d7abacd7d60e44549327991e/pkg/await-nodes.go#L47 for an expected log message. I'll have to investigate whether something is broken. If you have any logs to share, please leave them here (please beware not to share any credentials), they might help to understand the issue. Thanks!

**Comment by gesellix** [comment]
I changed the setup timeout in the docker-compose config to 60s. Can you please retry the current version?

**Comment by FlorianTolk** [comment]
Setting the timer to a minute did solve the issue, thanks!
Looking at the logs, it seems like the `cluster-setup` runs it's code first. Below is a section of the output:
```
Creating couchdbclusterconfigmaster_cluster-setup_1 ... done
Creating couchdbclusterconfigmaster_couchdb1_1      ... done
Creating couchdbclusterconfigmaster_couchdb2_1      ... done
Creating couchdbclusterconfigmaster_couchdb3_1      ... done
Attaching to couchdbclusterconfigmaster_cluster-setup_1, couchdbclusterconfigmaster_couchdb1_1, couchdbclusterconfigmaster_couchdb2_1, couchdbclusterconfigmaster_couchdb3_1
cluster-setup_1  | Going to setup the following nodes as cluster
cluster-setup_1  | [172.16.238.11 172.16.238.12 172.16.238.13]
cluster-setup_1  | tick@172.16.238.12:5984
cluster-setup_1  | tick@172.16.238.13:5984
cluster-setup_1  | tick@172.16.238.11:5984
 <continue for 193 lines>
cluster-setup_1  | tick@172.16.238.11:5984
 <other services begin running>
```

For a more graceful solution, is there a way to delay the setup service starting until the other services have had a few seconds to start up?

**Comment by gesellix** [comment]
I could add an option like `delay`, but I'd like to set it to a small default value, because on some systems the services are available after a short time - or might even be running already -, so adding a another delay would add a constant amount of time before the cluster is configured.

Another option is to add another tool to the stack, which checks for the services' availability. See https://github.com/gesellix/couchdb-prometheus-exporter/blob/ef76f4757993cd16f963da16e74d5bcb6a3a1c70/examples/stack/docker-stack-single.yml#L18 for an example using a `wait-for` script.

I'll add the `delay` config option and get back to you soon so that you can give some feedback how big the delay on your system should to be.

**Comment by gesellix** [comment]
You can now define a custom setup delay (defaults to 5s). See https://github.com/gesellix/couchdb-cluster-config/commit/bff48788381b9c97875242ca371a2d6bb2f80ed3 for an example in the repo's docker-compose.yml. With 20s the user experience on my Windows box was better, when the CouchDB container had to be created. For already existing CouchDB containers, 5s delay seemed to be a better value.

Please give it a try and leave some feedback here - I'm then going to tag a new release. From my perspective the issue has been resolved, but feel free to tell me in case I've missed something!

**Comment by gesellix** [comment]
This one has been tagged as Rev 11: https://github.com/gesellix/couchdb-cluster-config/releases/tag/11

**Comment by FlorianTolk** [comment]
Thanks!
